[package]
name = "btt-dive-planner"
version = "0.4.1"
description = "BTT Dive Planner – decompression and gas planner"
authors = ["BTT Explorers Hungary"]
edition = "2021"

[lib]
name = "btt_dive_planner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
